steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build image'
    args: [
      'build', 
      '--build-arg', 'MACHINE_PORT=${_MACHINE_PORT}',
      '--build-arg', 'MACHINE_IP=${_MACHINE_IP}',
      '-t', '${_PROXY_REGISTRY}/$PROJECT_ID/${_PROXY_NAME}:${_PROXY_VERSION}',
      '-t', '${_PROXY_REGISTRY}/$PROJECT_ID/${_PROXY_NAME}',
      '.'
    ]

images:
  - '${_PROXY_REGISTRY}/$PROJECT_ID/${_PROXY_NAME}:${_PROXY_TAG}'
  - '${_PROXY_REGISTRY}/$PROJECT_ID/${_PROXY_NAME}:${_PROXY_VERSION}'

tags: ['PROXY','NGINX']

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROXY_REGISTRY: "gcr.io"
  _PROXY_VERSION:  "1.0.2"
  _PROXY_TAG:      "latest" 
  _PROXY_NAME:     "lb-proxy" 
  _MACHINE_IP:     "10.1.0.6"
  _MACHINE_PORT:   "8080"
